### ISSUE TITLE
.\Git\mingw64\share\doc\git-doc

### ISSUE THREAD

**Issue by code-wgl** [apachecn/git-doc-zh#2]
如果能按照，本地git目录下（.\Git\mingw64\share\doc\git-doc）的网页文档翻译就好了。

**Comment by wizardforcel** [comment]
这个不打算给 bash manual 用。

**Comment by wizardforcel** [comment]
以 md 格式翻译是为了便于协作，翻译完成后可以将他们编译成 html。
